# -*- coding: utf-8 -*-
"""Graph Module

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zCRfI3C379ZojcJ8EB5Oz4W6PrJ5jctV
"""

#%pip install plotly
import plotly.graph_objects as go
import pandas as pd
import matplotlib.pyplot as plt
import csv

ex_df = pd.read_csv('ag_input1.txt', sep=",", names=["Worker", "Date", "Term", "Link", "Label"])

final_label = {}
link_date = {}
date_count = {}

# process mturk results
for _, x in ex_df.iterrows():
  worker = x["Worker"]
  date = x["Date"]
  term = x["Term"]
  link = x["Link"]
  label = x["Label"]

  final_label[link] = True if label == "Yes" else False
  link_date[link] = date

# get the # of articles based on date
for k, v in final_label.items():
  if link_date[k] not in date_count:
    date_count[link_date[k]] = 0
  date_count[link_date[k]] += 1 if v else 0

# show graph over time
gx = sorted(date_count)
gy = [date_count[x] for x in gx]
plt.plot(gx, gy)
plt.gcf().autofmt_xdate()
plt.title("Asian hate crimes over time")
plt.show()

###############################

states_data = {"AL": 0,
               "AK": 0,
               "AZ": 0,
               "AR": 0,
               "CA": 0,
               "CO": 0,
               "CT": 0,
               "DE": 0,
               "FL": 0,
               "GA": 0,
               "HI": 0,
               "ID": 0,
               "IL": 0,
               "IN": 0,
               "IA": 0,
               "KS": 0,
               "KY": 0,
               "LA": 0,
               "ME": 0,
               "MD": 0,
               "MA": 0,
               "MI": 0,
               "MN": 0,
               "MS": 0,
               "MO": 0,
               "MT": 0,
               "NE": 0,
               "NV": 0,
               "NH": 0,
               "NJ": 0,
               "NM": 0,
               "NY": 0,
               "NC": 0,
               "ND": 0,
               "OH": 0,
               "OK": 0,
               "OR": 0,
               "PA": 0,
               "RI": 0,
               "SC": 0,
               "SD": 0,
               "TN": 0,
               "TX": 0,
               "UT": 0,
               "VT": 0,
               "VA": 0,
               "WA": 0,
               "WV": 0,
               "WI": 0,
               "WY": 0}

us_state_abbrev = {
    'Alabama': 'AL',
    'Alaska': 'AK',
    'American Samoa': 'AS',
    'Arizona': 'AZ',
    'Arkansas': 'AR',
    'California': 'CA',
    'Colorado': 'CO',
    'Connecticut': 'CT',
    'Delaware': 'DE',
    'District of Columbia': 'DC',
    'Florida': 'FL',
    'Georgia': 'GA',
    'Guam': 'GU',
    'Hawaii': 'HI',
    'Idaho': 'ID',
    'Illinois': 'IL',
    'Indiana': 'IN',
    'Iowa': 'IA',
    'Kansas': 'KS',
    'Kentucky': 'KY',
    'Louisiana': 'LA',
    'Maine': 'ME',
    'Maryland': 'MD',
    'Massachusetts': 'MA',
    'Michigan': 'MI',
    'Minnesota': 'MN',
    'Mississippi': 'MS',
    'Missouri': 'MO',
    'Montana': 'MT',
    'Nebraska': 'NE',
    'Nevada': 'NV',
    'New Hampshire': 'NH',
    'New Jersey': 'NJ',
    'New Mexico': 'NM',
    'New York': 'NY',
    'North Carolina': 'NC',
    'North Dakota': 'ND',
    'Northern Mariana Islands':'MP',
    'Ohio': 'OH',
    'Oklahoma': 'OK',
    'Oregon': 'OR',
    'Pennsylvania': 'PA',
    'Puerto Rico': 'PR',
    'Rhode Island': 'RI',
    'South Carolina': 'SC',
    'South Dakota': 'SD',
    'Tennessee': 'TN',
    'Texas': 'TX',
    'Utah': 'UT',
    'Vermont': 'VT',
    'Virgin Islands': 'VI',
    'Virginia': 'VA',
    'Washington': 'WA',
    'West Virginia': 'WV',
    'Wisconsin': 'WI',
    'Wyoming': 'WY'
}

pre_df = pd.read_csv("ag_input2.csv")
for _, x in pre_df.iterrows():
  state = x["state"]
  if state != "Unknown" and state != "Not in the US":
    states_data[us_state_abbrev[state]] += 1

with open('statecount.csv', "w") as f:
  writer = csv.writer(f)
  cols = writer.writerow(['state', 'incidents'])
  for k, v in states_data.items():
    writer.writerow((k, v))

df = pd.read_csv("statecount.csv")

scl = [[0.0, 'rgb(242,240,247)'], [0.2, 'rgb(218,218,235)'], [0.4, 'rgb(188,189,220)'], 
       [0.6, 'rgb(158,154,200)'], [0.8, 'rgb(117,107,177)'], [1.0, 'rgb(84,39,143)']]

data = [dict(
        type='choropleth',
        colorscale = scl,
        autocolorscale = False,
        locations = df['state'],
        z = df['incidents'],
        locationmode = 'USA-states',
        marker = dict(
            line = dict (
                color = 'rgb(255,255,255)',
                width = 2
            )
        ),
        colorbar = dict(
            title = "Number of Incidents"
        )
    )]

layout = dict(
        title = 'Asian Hate Crimes by State',
        geo = dict(
            scope='usa',
            projection=dict(type='albers usa'),
            showlakes = True,
            lakecolor = 'rgb(255, 255, 255)',
        ),
    )
    
fig = go.Figure(data=data, layout=layout)
fig.show()