# -*- coding: utf-8 -*-
"""Quality Control

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lElXbk7FChcYna6157YJwJQ08CTU8_Qd
"""

import pandas as pd


def majority_vote(mturk_res):
    keep_cols = ["Input.url", "Answer.asian_hate_crime", "Answer.reference_hate"]

    mturk_res = mturk_res[keep_cols]
    data = {}
    for index, row in mturk_res.iterrows():
        attr_id = row['Input.url']
        if attr_id not in data.keys():
            data[attr_id] = {}

        
        answer1 = row["Answer.asian_hate_crime"]
        answer2 = row["Answer.reference_hate"]

        dict_of_atts = data[attr_id]
        if attr_id not in dict_of_atts.keys():
            dict_of_atts[attr_id] = {'hate': 0, 'no_hate': 0, 'ref': 0, 'no_ref':0}
        if (answer1):
          dict_of_atts[attr_id]["hate"] = dict_of_atts[attr_id]["hate"] + 1
        else:
          dict_of_atts[attr_id]["no_hate"] = dict_of_atts[attr_id]["no_hate"] + 1
        if (answer2):
          dict_of_atts[attr_id]["ref"] = dict_of_atts[attr_id]["ref"] + 1
        else:
          dict_of_atts[attr_id]["no_ref"] = dict_of_atts[attr_id]["no_ref"] + 1


    out = []
    for id in data.keys():
        for adj in data[id].values():
            yes_hate = adj["hate"]
            no_hate = adj["no_hate"]
            yes_ref = adj["ref"]
            no_ref = adj["no_ref"]
            if (yes_hate > no_hate):
                if (yes_ref > no_ref):
                  out.append((id, True, True))
                else: 
                  out.append((id, True, False))
            else:
                if (yes_ref > no_ref):
                  out.append((id, False, True))
                else: 
                  out.append((id, False, False))
                

    return sorted(out)

def main():
    # Read in CVS result file with pandas

    results = pd.read_csv('/content/drive/MyDrive/First Real HIT results.csv')

    # output1.csv
    pd.DataFrame(majority_vote(results), columns=["article_id", "Hate_Crime", "Reference_Hate"]).to_csv('output.csv', index=False)
  
if __name__ == '__main__':
    main()