# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LU8_U4GXid_5ztgnnYDkgvHFsN9Rxz1u
"""

import pandas as pd
import csv

def wrong_answers(results, raw_data):
  correct = {}
  df_results = pd.DataFrame(results)
  for index, row in df_results.iterrows():
    correct[row["article_id"]] = [str(row["Hate_Crime"]).lower(), str(row["Reference_Hate"]).lower()]

  df_raw = pd.DataFrame(raw_data)

  for index, row in df_raw.iterrows():
    if row["Answer.asian_hate_crime"] != correct[row["Input.url"]][0] or row["Answer.reference_hate"] != correct[row["Input.url"]][1]:
      df_raw.loc[index, 'Reject'] = "Your answer for this HIT was incorrect"
    else:
      df_raw.loc[index, 'Approve'] = "x"

  return df_raw

def main():
  raw_data = pd.read_csv('Results for HIT Two.csv')
  results = pd.read_csv('output2 (1).csv')
  acceptedRejected = wrong_answers(results, raw_data)
  #display(acceptedRejected)

  acceptedRejected.to_csv(r'output.csv')

if __name__ == '__main__':
    main()